# Dependencies
markdown:         kramdown
highlighter:      Rouge

# Permalinks
permalink:        pretty

# Setup
title:            Hyde
tagline:          'A Jekyll theme'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              https://rsyamil.github.io/syamilrazak.io/
baseurl:          /syamilrazak.io/

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5
gems: [jekyll-paginate,jekyll-gist]
plugins: [jekyll-paginate]
paginate_path: "page:num"

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

theme: jekyll-theme-cayman